title: mirgee's blog
author:
  name: Miroslav Kovar
  email: miroslavkovar@protonmail.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

minima:
  skin: auto
  date_format: "%b-%d-%Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/jekyll/mirgee" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/miroslav-kovar-a9b06b115" }
    - { platform: stackoverflow,  user_url: "https://stackexchange.com/users/4049915/mirgee" }

header_pages:
  - index.md

show_excerpts: false

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
